Update rtd 01
aboutcode-org/scancode-workbench pull request #431
Opened 2020-03-20 22:50 UTC by johnmhoran

2020-03-22 11:32 UTC, steven-esser requested changes
This looks good, content-wise. 

I left a few comments, mostly on the css override file. The repetition is only there to point out all the various instances. Other than that, this looks good.

2020-03-22 11:32 UTC, majurg commented on .gitignore
> +docs-update/build
Now that everything is in `docs/` I do not think we need this entry here.

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +} */
Is this block needed? I would remove it since we do not use it at all, unless there is a good reason to keep it around.

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    font-size: 13px;
Why do we have two different font-size values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    font-size: 16px;
Why do we have two different font-size values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    font-weight: normal;
Why do we have two different font-weight values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    padding: 5px 10px 5px 10px;
Why do we have two different padding values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    font-size: 13px;
Why do we have two different font-size values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    line-height: 1.5;
Why do we have two different line-height values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    border: 0;
Why do we have two different border values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    background-color: #f5f5f5;
Why do we have two different background-color values here?

2020-03-22 11:32 UTC, majurg commented on docs/source/_static/theme_overrides.css
> +    margin-bottom: 0px;
Why do we have two different margin-bottom values here?

2020-03-22 11:32 UTC, majurg commented on docs/scripts/doc8_style_check.sh
> +doc8 --max-line-length 100 source --ignore D000 --quiet
I think this change is causing the build failures. See: https://travis-ci.org/github/nexB/scancode-workbench/jobs/665056824#L270

2020-03-23 19:50 UTC, steven-esser approved these changes

2020-03-23 19:51 UTC, majurg commented
Something if off with Travis connection to PRs, but the build have passed so I am merging this.

2020-03-23 19:51 UTC, merged

2020-03-23 19:52 UTC, johnmhoran commented
@majurg Yes, I've been tracking this, the last Travis test passed but GH was showing it in progress, was writing a post to you.