Updating pull request
aboutcode-org/scancode-workbench pull request #490
Opened 2021-03-24 12:57 UTC by Dinesh101041

2021-03-25 15:34 UTC, majurg requested changes

2021-03-25 15:34 UTC, majurg commented on .github/ISSUE_TEMPLATE/bug-.md
> +4. please simplify the steps as much as possible so they do not require additional resources to run,
This is not really relevant to an Electron GUI application.

2021-03-25 16:23 UTC, Dinesh101041 commented on .github/ISSUE_TEMPLATE/bug-.md
> +4. please simplify the steps as much as possible so they do not require additional resources to run,
Changed sir please check

2021-03-26 15:14 UTC, majurg requested changes
@Dinesh101041 Thank you. Can you please sign off your commits and rebase them into a single, signed commit?

2021-03-26 16:03 UTC, Dinesh101041 commented
Sir can your explain more what to do  because  i am not well in DCO workflow and i make the pull request through github web ui so unable to run a force command 
or can i delete the pull request and branch and make a new pull request sir

2021-03-26 16:05 UTC, Pratikrocks commented
Hi @Dinesh101041 just put the flag `-s` when you are making the commit.
Its is better to use the CLI always

2021-03-26 17:39 UTC, Dinesh101041 commented
Thank you sir i will do it 
in between i ran into another doubt when setting scancode-workbench locally using node js
i cloned the repo and done the `npm install` command 
after that how to run a 'Rebuild native Node.js modules against the app version of Node.js'  for windows 
i run this command ` .\node_modules\.bin\electron-rebuild.cmd`but it shows error
and after the running  above command and npm start command we can upload a file into application?
 i am asking because of first time i run the `npm run ` command without  running rebulid native command  the application is launched but i am unable to upload files 

can you help me out sir

2021-03-26 17:58 UTC, Pratikrocks commented
I didn't get u correctly , u are not able to upload in git?

2021-03-26 18:11 UTC, Dinesh101041 commented
no sir after running npm start command 
the application is launched 
![image](https://user-images.githubusercontent.com/59551894/112674965-93baf180-8e8c-11eb-80e6-8a3cbc227bc0.png)

but after clicking `import json` or `open sql` buttons i did not get any response sir

2021-03-26 18:13 UTC, Pratikrocks commented
can you post the console logs if any?

2021-03-27 12:50 UTC, Dinesh101041 commented
Sorry for late reply sir here is console log 
![image](https://user-images.githubusercontent.com/59551894/112721181-8d7a5300-8f28-11eb-85fa-bc27c9bc7872.png)

2021-03-27 13:24 UTC, Pratikrocks commented
@Dinesh101041 ki think it's due to py version mismatch , deactivate the anaconda environment and give a try once

2021-03-28 13:23 UTC, Dinesh101041 commented
done a rebase sir

2021-03-28 13:31 UTC, Pratikrocks commented
@Dinesh101041 okay , just signoff commits

2021-03-28 13:41 UTC, Dinesh101041 commented
please check now sir

2021-04-13 06:40 UTC, Aayush-hub commented
@Dinesh101041 You DCO check failure suggests that you didn't sign off the commits. Please run followings commands :
- `git rebase HEAD~9 --signoff`
- `git push --force-with-lease origin develop`

2021-04-13 08:20 UTC, Dinesh101041 commented
i am getting merging conflicts on signof commit sir i am closing this pull request and create new one with all updation

2021-04-13 08:20 UTC, closed without merging