UI improvements in Dependencies dashboard & Packages explorer
aboutcode-org/scancode-workbench pull request #594
Opened 2023-08-02 08:11 UTC by OmkarPh

2023-08-07 14:24 UTC, AyanSinhaMahapatra requested changes
@OmkarPh thanks++ updates look good!
A couple of nits for your consideration.

1. In the left main views section and the `view` in the bar above we have `Packages Explorer`, but once you're there the header is `Packages and Dependencies explorer`. We have to be consistent here and use only one. I'm leaning towards `Packages Explorer` here, but your call.
2. In the `Packages Explorer` when you click on one of the dependencies on the left, you have the details with the dependency attributes and their values. The you have their respective raw JSON there but it's titled `Raw package`, it should be `Raw dependency` instead?
3. In the dependency info dashboard, in the table of values by package type, we have a `No Value detected` there. I'm not sure we have PURLs without package types here, do you have an example of this? In any case let me check SCTK if there are actual instances of these. If not we can remove this row, and irrespective of that, we should only show this if there are values with no package type.
4. In the dependency info dashboard, in the table of values by package type, maybe we should have a title for the table like we have for other charts?
5. In the new dependencies table (and now that I notice it in the license matches table too similarly) we have empty space on the right in case of larger screens or even if you do full screen in smaller screens, while we still have some fields which are collapsed to a the second line. Do you think we can set these column values set such as we have minimum values for these, which will be there and then henceforth if it has more space than sum of the minimum of the column widths, we expand only some columns by proportions (while keeping smaller ones fixed). This is an enhancement and minor, if possible.

2023-08-07 15:48 UTC, mjherzog commented
A minor point but names like Packages Explorer should be singular in most cases - e.g., Package Explorer

2023-08-08 18:19 UTC, OmkarPh commented
> 1. In the left main views section and the `view` in the bar above we have `Packages Explorer`, but once you're there the header is `Packages and Dependencies explorer`. We have to be consistent here and use only one. I'm leaning towards `Packages Explorer` here, but your call.

Yep, having only `Package Explorer` makes sense.


> 2. In the `Packages Explorer` when you click on one of the dependencies on the left, you have the details with the dependency attributes and their values. Then you have their respective raw JSON there but it's titled `Raw package`, it should be `Raw dependency` instead?

My bad, it has to be `Raw dependency`

2023-08-08 18:22 UTC, OmkarPh commented
> 4. In the dependency info dashboard, in the table of values by package type, maybe we should have a title for the table like we have for other charts?

I don't have a good title on top of my head, but what would be a good word to collectively represent `Runtime`, `Optional` & `Resolved`

2023-08-08 18:26 UTC, mjherzog commented
The name that we usually use for Runtime, Optional etc. Dependency Scope.

2023-08-08 18:26 UTC, OmkarPh commented
> 3. In the dependency info dashboard, in the table of values by package type, we have a `No Value detected` there. I'm not sure we have PURLs without package types here, do you have an example of this? In any case let me check SCTK if there are actual instances of these. If not we can remove this row, and irrespective of that, we should only show this if there are values with no package type.

Actually, I didn't get this `No value detected` anywhere, Can you send me the particular scan, I'll have a look
For example,
![image](https://github.com/nexB/scancode-workbench/assets/48476025/38dff513-57aa-4dac-80ee-90202539391b)

2023-08-08 18:38 UTC, OmkarPh commented
> The name that we usually use for Runtime, Optional etc. Dependency Scope.

I can think of some options:
* `Dependency Scope summary by Package Type`
* `Dependency Scope summary across Package Types`

2023-08-09 08:12 UTC, AyanSinhaMahapatra commented
> Actually, I didn't get this No value detected anywhere, Can you send me the particular scan, I'll have a look
For example,

Sure, here's a scan that had this value, attaching a screenshot too.
[elasticsearch_v32rc4.json.txt](https://github.com/nexB/scancode-workbench/files/12299841/elasticsearch_v32rc4.json.txt)
![no_value_detected](https://github.com/nexB/scancode-workbench/assets/25746274/23ac54df-5775-4a1c-b15b-7bf949625810)

I checked other JSONs and this does not seem to be present in all of them.

Also just a nit, notice how the table has only a few rows but takes up a lot more space than necessary, we should probably reduce the table height when there's not enough rows?

2023-08-14 16:55 UTC, OmkarPh commented
Hi @AyanSinhaMahapatra 
I've done the changes requested

For the table height, there are some other changes in other branches which need to be taken into account, hence it is tracked separately in #598

2023-08-22 13:58 UTC, AyanSinhaMahapatra approved these changes
LGTM!
Thanks++ @OmkarPh , feel free to merge this.

2023-08-22 13:58 UTC, AyanSinhaMahapatra commented on src/pages/Packages/miscInfo.ts
> +// Obtaining a misc package via function to prevent preserving the same object across rerenders
Nice!

2023-08-23 04:12 UTC, OmkarPh commented
Thanks @AyanSinhaMahapatra 
Merging this

2023-08-23 04:12 UTC, merged